version: "3.8"

services:
  app_publication:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    environment:
      - DB_DATABASE=$DB_DATABASE
      - DB_HOST=$DB_HOST
      - DB_PASS=$DB_PASS
      - DB_USER=$DB_USER
      - DB_PORT=$DB_PORT

      - JWT_EXPIRE=$JWT_EXPIRE
      - JWT_SECRET=$JWT_SECRET
      - PAGE_NUMBER=$PAGE_NUMBER
      - PAGE_SIZE=$PAGE_SIZE
      - USER_ADMIN=$USER_ADMIN
      - PASS_ADMIN=$PASS_ADMIN
      - ADMIN_ROLE=$ADMIN_ROLE
      - PORT=$PORT


    container_name: app_publication
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    ports:
      - "3000:3000"  
  