export enum ValidPermits {
    SUPER_ADMIN = 'PCALL01',

    CREATE_EMPLOYEE = 'PCE001',
    READ_EMPLOYEE = 'PRE001',
    UPDATE_EMPLOYEE = 'PUE001',
    DELETE_EMPLOYEE = 'PDE001',

    CREATE_USER = 'PCU001',
    READ_USER = 'PRU001',
    UPDATE_USER = 'PUU001',
    DELETE_USER = 'PDU001',

    CREATE_ROLE = 'PCR001',
    READ_ROLE = 'PRR001',
    UPDATE_ROLE = 'PUR001',
    DELETE_ROLE = 'PDR001',

    CREATE_PUBLICATION = 'PCR001',
    READ_PUBLICATION = 'PRR001',
    UPDATE_PUBLICATION = 'PUR001',
    DELETE_PUBLICATION = 'PDR001',

    READ_PERMIT = 'PRPM01',
    UPDATE_PERMIT = 'PUPM01',
}