
name: DeploitApp

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: node:16-alpine
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install nestjs and pm2
    - run : |
        npm i -g @nestjs/cli
        npm install --only=production
        npm install -g pm2
        npm run build
    - name: Execute Proyect (pm2)
    - run: pm2 start ecosystem.config.js
    needs:
      - build
      - test
    
  test:
    runs-on: node:16-alpine
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install --only=development
    - name: Execute Test:e2e
    - run: npm run test:e2e
    needs:
      - build

  build:
    runs-on: node:16-alpine
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Crear archivo .env
      run: |
        echo "DB_DATABASE=${{secrets.DB_DATABASE}}" >> .env
        echo "DB_HOST=${{secrets.DB_HOST}}" >> .env
        echo "DB_PASS=${{secrets.DB_PASS}}" >> .env
        echo "DB_USER=${{secrets.DB_USER}}" >> .env
        echo "DB_PORT=${{secrets.DB_PORT}}" >> .env

        echo "JWT_EXPIRE=${{secrets.JWT_EXPIRE}}" >> .env
        echo "JWT_SECRET=${{secrets.JWT_SECRET}}" >> .env
        echo "PAGE_NUMBER=${{secrets.PAGE_NUMBER}}" >> .env
        echo "PAGE_SIZE=${{secrets.PAGE_SIZE}}" >> .env
        echo "USER_ADMIN=${{secrets.USER_ADMIN}}" >> .env
        echo "PASS_ADMIN=${{secrets.PASS_ADMIN}}" >> .env
        echo "ADMIN_ROLE=${{secrets.ADMIN_ROLE}}" >> .env
        echo "PORT=${{secrets.PORT}}" >> .env

