name: DeploitApp

on:
  push:
    branches: [ "main" ]
env:
  DB_DATABASE: ${{secrets.DB_DATABASE}}
  DB_HOST: ${{secrets.DB_HOST}}
  DB_PASS: ${{secrets.DB_PASS}}
  DB_USER: ${{secrets.DB_USER}}
  DB_PORT: ${{secrets.DB_PORT}}
  JWT_EXPIRE: ${{secrets.JWT_EXPIRE}}
  JWT_SECRET: ${{secrets.JWT_SECRET}}
  PAGE_NUMBER: ${{secrets.PAGE_NUMBER}}
  PAGE_SIZE: ${{secrets.PAGE_SIZE}}
  USER_ADMIN: ${{secrets.USER_ADMIN}}
  PASS_ADMIN: ${{secrets.PASS_ADMIN}}
  ADMIN_ROLE: ${{secrets.ADMIN_ROLE}}
  PORT: ${{secrets.PORT}}
jobs:
  deploy:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install nestjs and pm2
        run : |
          npm i -g @nestjs/cli
          npm install --only=production
          npm install -g pm2
          npm run build
      - name: Execute Proyect (pm2)
        run: pm2 start ecosystem.config.js
    needs:
      - test
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install --only=development
      - name: Execute Test:e2e
        run: npm run test:e2e

