# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: DeploitApp

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build --if-present

    # Detener y eliminar el proyecto solo si existe
    - run: |
        if pm2 describe publication-proyect &> /dev/null; then
          pm2 stop publication-proyect
          pm2 delete publication-proyect
        fi
      shell: bash

    - run: npm run test:e2e
    - run: pm2 start ecosystem.config.js
